<-PYT:import socket
<-PYT:socket.gethostname()
->RET:'gewoia'
<-PYT:socket.AF_INET
->RET:2
<-PYT:socket.SOCK_STREAM
->RET:1
<-PYT:socket.socket(2, 1)
->RET:Instance('_socketobject(object)', '_socketobject1')
<-PYT:_socketobject1.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror1')
<-PYT:time.sleep(1)
<-PYT:_socketobject1.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror2')
<-PYT:time.sleep(1)
<-PYT:_socketobject1.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror3')
<-PYT:time.sleep(1)
<-PYT:_socketobject1.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror4')
<-PYT:time.sleep(1)
<-PYT:_socketobject1.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror5')
<-PYT:time.sleep(1)
<-PYT:gaierror5.__str__()
->RET:'[Errno -2] Name or service not known'
<-PYT:socket.socket(2, 1)
->RET:Instance('_socketobject(object)', '_socketobject2')
<-PYT:_socketobject2.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror6')
<-PYT:time.sleep(1)
<-PYT:_socketobject2.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror7')
<-PYT:time.sleep(1)
<-PYT:_socketobject2.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror8')
<-PYT:time.sleep(1)
<-PYT:_socketobject2.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror9')
<-PYT:time.sleep(1)
<-PYT:_socketobject2.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror10')
<-PYT:time.sleep(1)
<-PYT:gaierror10.__str__()
->RET:'[Errno -2] Name or service not known'
<-PYT:socket.socket(2, 1)
->RET:Instance('_socketobject(object)', '_socketobject3')
<-PYT:_socketobject3.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror11')
<-PYT:time.sleep(1)
<-PYT:_socketobject3.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror12')
<-PYT:time.sleep(1)
<-PYT:_socketobject3.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror13')
<-PYT:time.sleep(1)
<-PYT:_socketobject3.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror14')
<-PYT:time.sleep(1)
<-PYT:_socketobject3.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror15')
<-PYT:time.sleep(1)
<-PYT:gaierror15.__str__()
->RET:'[Errno -2] Name or service not known'
<-PYT:socket.socket(2, 1)
->RET:Instance('_socketobject(object)', '_socketobject4')
<-PYT:_socketobject4.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror16')
<-PYT:time.sleep(1)
<-PYT:_socketobject4.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror17')
<-PYT:time.sleep(1)
<-PYT:_socketobject4.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror18')
<-PYT:time.sleep(1)
<-PYT:_socketobject4.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror19')
<-PYT:time.sleep(1)
<-PYT:_socketobject4.connect(('no_such_machine', 42))
->RET:raise Instance('gaierror(error, exceptions.IOError)', 'gaierror20')
<-PYT:time.sleep(1)
<-PYT:gaierror20.__str__()
->RET:'[Errno -2] Name or service not known'
